version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg15
    container_name: dailystoic-db
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dailystoic-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "8082:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NGINX_CONF: nginx.conf
        REACT_APP_API_URL: http://localhost
    container_name: dailystoic-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
